[package]
name = "sqlx-example-sqlite-todos"
version = "0.1.0"
edition = "2018"
workspace = "../../../"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
futures = "0.3"
clap = { version = "4", features = ["derive"] }

#[target.'cfg(target_arch = "wasm")'.dependencies]
sqlx = { path = "../../../", features = ["sqlite", "runtime-tokio"] }


#[target.'cfg(not(target_arch = "wasm"))'.dependencies]
#tokio = { version = "1.20.0", features = ["rt", "macros"] }
#sqlx = { path = "../../../", features = [ "sqlite", "runtime-tokio", "tls-native-tls" ] }
